### ISSUE TITLE
Konzept: Zusammenfassen von Objekten in Projekten

### ISSUE THREAD

**Issue by Hutmensch** [InspirerHWR2020/App#13]
Projekte = Kategorien

**Comment by KuroKurama01** [comment]
Kategorisierung wie z.B. bei Telegram-Emojis: Überkategorien eher grob, innerhalb davon dann Objekte von verschiedenen Typen (mehrere Bänke hintereinander)

![Image](https://user-images.githubusercontent.com/33878947/198894423-b422b5fe-f37f-48fe-ad32-e7f8e2a76798.jpg)
